/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Scene_s_03.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Scene2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Scene_s_03.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[-0.001, -0.75, 3.8]}>
          <group name="Empty" position={[0.069, 0.629, -1.134]}>
            <group name="Cube" position={[1.354, -4.942, 5.565]} rotation={[0, 0, -Math.PI / 2]} scale={0.921}>
              <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['M_Metal.001']} />
              <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['M_Metal.002']} />
              <mesh name="Text" geometry={nodes.Text.geometry} material={materials.M_white} position={[-0.182, -1.104, 1.296]} rotation={[Math.PI / 2, 0, 0]} scale={0.103} />
              <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials.M_white} position={[-0.182, -0.212, 1.296]} rotation={[Math.PI / 2, 0, 0]} scale={0.103} />
            </group>
            <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['M_Metal.002']} position={[0, -1.309, 0]} />
            <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['M_Metal.002']} position={[-4.594, -4.942, 5.565]} rotation={[0, 0, -Math.PI / 2]} scale={0.921} />
            <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.M_ground} position={[0, -1.309, 0]}>
              <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.M_black_transp} position={[-0.448, -3.662, 5.546]} scale={[0.426, 0.488, 0.488]} />
              <group name="Cube016" position={[-0.448, -3.662, 5.546]} scale={[0.426, 0.488, 0.488]}>
                <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.M_ground} />
                <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials.M_Services_Simulation_Content} />
                <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials.M_white} position={[0.227, 2.117, 0.307]} rotation={[Math.PI / 2, -1.571, 0]} scale={[0.257, 0.257, 0.294]} />
              </group>
              <group name="Cube017" position={[-1.325, -3.662, 5.55]} scale={[0.426, 0.488, 0.488]}>
                <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.M_ground} />
                <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials.M_Services_Simulation_Content} />
                <mesh name="Cube021_2" geometry={nodes.Cube021_2.geometry} material={materials.M_black_transp} />
                <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials.M_white} position={[0.494, 2.117, 0.298]} rotation={[Math.PI / 2, -1.571, 0]} scale={[0.257, 0.257, 0.294]} />
              </group>
              <group name="Cube018" position={[-2.205, -3.662, 5.543]} scale={[0.426, 0.488, 0.488]}>
                <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.M_ground} />
                <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials.M_Services_Game_Exp} />
                <mesh name="Cube022_2" geometry={nodes.Cube022_2.geometry} material={materials.M_black_transp} />
                <mesh name="Text004" geometry={nodes.Text004.geometry} material={materials.M_white} position={[0.533, 2.117, 0.312]} rotation={[Math.PI / 2, -1.571, 0]} scale={[0.257, 0.257, 0.294]} />
              </group>
              <group name="Cube019" position={[-3.093, -3.662, 5.546]} scale={[0.426, 0.488, 0.488]}>
                <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.M_ground} />
                <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials.M_Services_Game_Exp} />
                <mesh name="Cube023_2" geometry={nodes.Cube023_2.geometry} material={materials.M_black_transp} />
                <mesh name="Text005" geometry={nodes.Text005.geometry} material={materials.M_white} position={[0.524, 2.117, 0.307]} rotation={[Math.PI / 2, -1.571, 0]} scale={[0.257, 0.257, 0.294]} />
              </group>
              <pointLight name="Point005" intensity={40} decay={2} color="#e283ff" position={[-3.922, 1.525, 0.623]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point001_1" intensity={40} decay={2} color="#b2c5ff" position={[-3.631, -1.059, 11.731]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point002" intensity={40} decay={2} color="#5350ff" position={[0.642, -1.301, 4.801]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point003" intensity={40} decay={2} color="#70b4ff" position={[-0.066, -0.129, 2.856]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point004" intensity={40} decay={2} color="#fd4bff" position={[-0.629, -1.302, 4.8]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point006" intensity={40} decay={2} color="#bdb8ff" position={[1.583, -2.661, 6.246]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point007" intensity={40} decay={2} color="#bdb8ff" position={[1.583, -4.653, 6.246]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point008_1" intensity={40} decay={2} color="#8f84ff" position={[-3.83, -2.661, 5.08]} rotation={[-Math.PI / 2, 0, 0]} />
              <pointLight name="Point009_1" intensity={40} decay={2} color="#cd80ff" position={[-3.83, -4.777, 5.08]} rotation={[-Math.PI / 2, 0, 0]} />
              <spotLight name="Spot001" intensity={20} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#70b4ff" position={[-0.066, -0.211, 3.155]} rotation={[-2.599, 0, 0]}>
                <group position={[0, 0, -1]} />
              </spotLight>
              <group name="Cube013_1" position={[-0.066, 0.309, 2.851]} scale={0.146}>
                <mesh name="Cube017_1" geometry={nodes.Cube017_1.geometry} material={materials.M_llight_base} />
                <mesh name="Cube017_2" geometry={nodes.Cube017_2.geometry} material={materials['Material.002']} />
              </group>
              <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.M_ground} position={[0, -2.907, 4.139]}>
                <group name="VX1_Body" position={[-0.068, 4.42, -0.623]}>
                  <mesh name="FBPlayer_Body001" geometry={nodes.FBPlayer_Body001.geometry} material={materials.M_VX1_body2} />
                  <mesh name="FBPlayer_Body001_1" geometry={nodes.FBPlayer_Body001_1.geometry} material={materials.M_glass_face_gltf} />
                  <mesh name="FBPlayer_Body001_2" geometry={nodes.FBPlayer_Body001_2.geometry} material={materials.M_glass_face} />
                  <mesh name="FBPlayer_Body001_3" geometry={nodes.FBPlayer_Body001_3.geometry} material={materials.M_face} />
                </group>
              </mesh>
              <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.M_ground} position={[-3.271, 2.775, 0.895]} scale={0.78} />
              <mesh name="Cube020_2" geometry={nodes.Cube020_2.geometry} material={materials.M_emissive03} position={[-0.066, -3.061, 4.139]} />
              <mesh name="Cube021_3" geometry={nodes.Cube021_3.geometry} material={materials.M_emissive03} position={[-0.066, -4.98, 4.132]} />
              <mesh name="Vertex_Icon" geometry={nodes.Vertex_Icon.geometry} material={materials['Material.001']} position={[-0.697, 1.401, 1.137]} rotation={[Math.PI / 2, 0, -0.645]} scale={[0.209, 0.554, 0.191]} />
            </mesh>
          </group>
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={32.269} rotation={[-0.041, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Scene_s_03.glb')
